name: CI/CD Pipeline

on:
  push:
    branches: [main]
    paths:
      - 'index.html'
      - 'assets/**'
      - 'css/**'
      - 'js/**'
      - '!README.md'  # Explicitly exclude non-relevant files

jobs:
  deploy_website:
    name: Deploy Website
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for proper changed files detection

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Upload to S3
        run: |
          # Debug changed files
          echo "Changed files:"
          git diff --name-only HEAD^ HEAD
          
          # Sync only relevant files
          aws s3 sync . s3://inventoryapp.rrc.ca \
            --exclude "*" \
            --include "index.html" \
            --include "assets/*" \
            --include "css/*" \
            --include "js/*" \
            --acl public-read \
            --cache-control "max-age=3600"

      - name: Invalidate CloudFront cache
        if: success()
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
