name: Deploy Python functions to AWS Lambda

on:
  push:
    branches:
      - 'main'
    paths:
      - 'lambda/**/lambda_function.py'  # Only run when a lambda_function.py is modified

jobs:
  deploy:
    name: Deploy Updated Lambda Functions
    runs-on: ubuntu-latest

    strategy:
      matrix:
        function:
          - get_all_inventory_items
          - get_inventory_item
          - add_inventory_item
          - delete_inventory_item
          - get_location_inventory_items

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v4.0.2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Zip Lambda function
        run: |
          cd lambda/${{ matrix.function }}
          zip -r ../../${{ matrix.function }}.zip .

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ matrix.function }} \
            --zip-file fileb://${{ matrix.function }}.zip \
            --publish

      - name: Cleanup
        run: rm ${{ matrix.function }}.zip
