name: Deploy Website to S3 Bucket

on:
  push:
    branches:
      - main
    paths:
      - 'index.html'
      - 'assets/**'
      - 'css/**'
      - 'js/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      # 2. Configure AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      # 3. Verify files exist
      - name: Check files to deploy
        run: |
          echo "Files to be deployed:"
          ls -la index.html assets/ css/ js/

      # 4. Upload to S3 (ACL-free version)
      - name: Upload files to S3
        run: |
          aws s3 sync . s3://finalproject-2025 \
            --exclude "*" \
            --include "index.html" \
            --include "assets/*" \
            --include "css/*" \
            --include "js/*" \
            --cache-control "max-age=3600"

      # 5. Set bucket policy for public access (if needed)
      - name: Configure public access
        run: |
          aws s3api put-bucket-policy \
            --bucket finalproject-2025 \
            --policy '{
              "Version": "2012-10-17",
              "Statement": [{
                "Effect": "Allow",
                "Principal": "*",
                "Action": "s3:GetObject",
                "Resource": "arn:aws:s3:::finalproject-2025/*"
              }]
            }'

      # 6. Invalidate CloudFront cache (optional)
      - name: Invalidate CloudFront cache
        if: success() && secrets.CLOUDFRONT_DISTRIBUTION_ID
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/index.html" "/assets/*" "/css/*" "/js/*"
