name: Deploy Website to S3 Bucket

on:
  push:
    branches:
      - 'main'
    paths:
      - 'index.html'
      - 'assets/**'
      - 'css/**'
      - 'js/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Upload files to S3
        run: |
          # Upload index.html with proper content type
          aws s3 cp index.html s3://finalproject-2025/ --content-type "text/html" --cache-control "max-age=3600"
          
          # Conditionally upload other directories if they exist
          if [ -d "assets" ]; then
            aws s3 cp assets/ s3://finalproject-2025/assets/ --recursive --cache-control "max-age=3600"
          fi
          
          if [ -d "css" ]; then
            aws s3 cp css/ s3://finalproject-2025/css/ --recursive --cache-control "max-age=3600"
          fi
          
          if [ -d "js" ]; then
            aws s3 cp js/ s3://finalproject-2025/js/ --recursive --cache-control "max-age=3600"
          fi
